# Generated by Django 4.0.1 on 2022-02-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='nft_image',
        ),
        migrations.RemoveField(
            model_name='nft_collection',
            name='profile_pic',
        ),
    ]
