# Generated by Django 4.0.1 on 2022-02-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bid_bidprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='minbidprice',
            field=models.FloatField(verbose_name='Minimum Bid Price'),
        ),
    ]
