# Generated by Django 4.0.1 on 2022-02-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_nft_nft_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft_collection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
