# Generated by Django 4.0.1 on 2022-02-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_nft_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft_bid',
            name='bidder_account_id',
        ),
        migrations.RemoveField(
            model_name='nft_bid',
            name='nft_id',
        ),
        migrations.RemoveField(
            model_name='nft_collection',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='nft_collection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='collection_name',
        ),
        migrations.AddField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Nft_Bid',
        ),
        migrations.DeleteModel(
            name='NFT_Collection',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
