# Generated by Django 4.0.1 on 2022-02-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_nft_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(default=55179, max_length=5),
        ),
    ]
