# Generated by Django 4.0.1 on 2022-02-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sell_minbidprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='minbidprice',
            field=models.FloatField(verbose_name='Minimum Bid Price (in ETH)'),
        ),
    ]
