# Generated by Django 4.0.1 on 2022-02-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_nft_token_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(default=36130, max_length=5),
        ),
    ]
