# Generated by Django 4.0.1 on 2022-02-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_nft_bid_bidder_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='blockchain',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
