# Generated by Django 4.0.1 on 2022-02-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_nft_token_id_sell'),
        ('main', '0005_hitcount_alter_nft_token_id'),
    ]

    operations = [
    ]
