# Generated by Django 4.0.1 on 2022-02-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_nft_blockchain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='nft_id',
            new_name='id',
        ),
    ]
