# Generated by Django 4.0.1 on 2022-02-23 14:46

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_hitcount_alter_nft_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidprice',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Bid Price'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='nft_name',
            field=models.CharField(max_length=50, verbose_name='NFT Name'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(default=main.models.random_token),
        ),
        migrations.AlterField(
            model_name='sell',
            name='minbidprice',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Minimum Bid Price'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='sale_ends',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Sale Ends'),
        ),
    ]
