# Generated by Django 4.0.1 on 2022-02-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_user_nft_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(default='token_id', max_length=5),
        ),
    ]
