# Generated by Django 4.0.1 on 2022-02-17 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_photo'),
        ('main', '0009_alter_nft_token_id'),
    ]

    operations = [
    ]
