# Generated by Django 4.0.1 on 2022-02-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_nft_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateField(verbose_name='bid date'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(default=16774, max_length=5),
        ),
    ]
