# Generated by Django 4.0.1 on 2022-02-18 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_nft_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(default=92669, max_length=5),
        ),
    ]
