# Generated by Django 4.0.1 on 2022-02-19 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_nft_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(default=60793, max_length=5),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_ends', models.DateTimeField(verbose_name='Sale Ends')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nft')),
            ],
        ),
    ]
