# Generated by Django 4.0.1 on 2022-02-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_bid_bidprice_alter_nft_token_id_delete_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidprice',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.IntegerField(default=88218, max_length=5),
        ),
    ]
